-- Active: 1668224935777@@127.0.0.1@3306@CATALOG

DROP TABLE WANT;
DROP TABLE BRAND;
DROP TABLE CTYPE;
DROP TABLE CLOTHING;
DROP TABLE SHOES;
DROP TABLE OUTFIT;
DROP TABLE EVENT_TYPE;



CREATE TABLE WANT
(  WantID INT NOT NULL,
   TypeID INT NOT NULL,
   WDescription VARCHAR(200) NOT NULL,
   WColor VARCHAR(45) NOT NULL,
   BrandID INT NOT NULL,
   Cost DECIMAL(12,2) NOT NULL,
   Link VARCHAR(2048) NOT NULL,
   Matches INT NOT NULL,
   WPriority VARCHAR(45) NOT NULL,
   CONSTRAINT PK_WANT PRIMARY KEY(WantID));

CREATE TABLE CLOTHING
(  ClothingID INT NOT NULL,
   CDescription VARCHAR(200) NOT NULL,
   TypeID INT NOT NULL,
   BrandID INT NOT NULL,
   Size VARCHAR(5) NOT NULL,
   CColor VARCHAR(45) NOT NULL,
   Rating INT,
   CFrenquency VARCHAR(45),
   CONSTRAINT PK_CLOTHING PRIMARY KEY(ClothingID)); 

CREATE TABLE SHOES
(  ShoeID INT NOT NULL,
   BrandID INT NOT NULL,
   SMake VARCHAR(45) NOT NULL,
   SName VARCHAR(45) NOT NULL,
   SColor VARCHAR(45) NOT NULL,
   Size DECIMAL(2,1) NOT NULL,
   ReleaseDate TIMESTAMP,
   BrokenIn VARCHAR(3) NOT NULL,
   CONSTRAINT PK_SHOES PRIMARY KEY(ShoeID)); 

CREATE TABLE OUTFIT
(  OutfitID INT NOT NULL,
   ClothingID INT NOT NULL,
   ShoeID INT NOT NULL,
   ODescription VARCHAR(200),
   EventID INT NOT NULL,
   Ranking INT,
   CONSTRAINT PK_OUTFIT PRIMARY KEY(OutfitID)); 

CREATE TABLE BRAND
(  BrandID INT NOT NULL,
   BName VARCHAR(45) NOT NULL,
   BMakes VARCHAR(200) NOT NULL,
   CONSTRAINT PK_BRAND PRIMARY KEY(BrandID)); 

CREATE TABLE EVENT_TYPE
(  EventID INT NOT NULL,
   EventType VARCHAR(45) NOT NULL,
   EFrequency VARCHAR(24) NOT NULL,
   CONSTRAINT PK_EVENT_TYPE PRIMARY KEY(EventID)); 

CREATE TABLE CTYPE
(  TypeID INT NOT NULL,
   ClothingType VARCHAR(45),
   CONSTRAINT PK_CTYPE PRIMARY KEY(TypeID)); 



ALTER TABLE WANT
  ADD CONSTRAINT FK_WANT_TypeID FOREIGN KEY (TypeID)
    REFERENCES CTYPE(TypeID);

ALTER TABLE WANT
  ADD CONSTRAINT FK_WANT_BrandID FOREIGN KEY (BrandID)
    REFERENCES BRAND(BrandID);  

ALTER TABLE WANT
  ADD CONSTRAINT FK_WANT_Matches FOREIGN KEY (Matches)
    REFERENCES CLOTHING(ClothingID);  

ALTER TABLE CLOTHING
  ADD CONSTRAINT FK_CLOTHING_TypeID FOREIGN KEY (TypeID)
    REFERENCES CTYPE(TypeID);

ALTER TABLE CLOTHING
  ADD CONSTRAINT FK_CLOTHING_BrandID FOREIGN KEY (BrandID)
    REFERENCES BRAND(BrandID);  

ALTER TABLE SHOES
  ADD CONSTRAINT FK_SHOES_BrandID FOREIGN KEY (BrandID)
    REFERENCES BRAND(BrandID);  

ALTER TABLE OUTFIT
  ADD CONSTRAINT FK_OUTFIT_EventID FOREIGN KEY (EventID)
    REFERENCES EVENT_TYPE(EventID);

ALTER TABLE OUTFIT
  ADD CONSTRAINT FK_OUTFIT_ShoeID FOREIGN KEY (ShoeID)
    REFERENCES SHOES(ShoeID);  

ALTER TABLE OUTFIT
  ADD CONSTRAINT FK_OUTFIT_ClothingID FOREIGN KEY (ClothingID)
    REFERENCES CLOTHING(ClothingID);